### ISSUE TITLE
Application crashing after waking up from sleep mode

### ISSUE THREAD

**Issue by RaasclartNinja** [Codectory/AutoHDR#61]
The application is open in the system tray but I notice when I go to launch a game that sometimes the application has crashed and is no longer running. I have to manually open it but I can't reproduce this consistently, it appears to just crash randomly in the background with no errors.

I have enabled the logfile and will update this once I experience the "crash" again, let me know how I can get any other useful information over to you.

**Comment by RaasclartNinja** [comment]
Attached the log file but it doesn't show any crash information. Seems to crash when I wake the computer up from sleep
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7694710/AutoHDR.log)
.

**Comment by RavenMacDaddy** [comment]
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7697658/AutoHDR.log)
[AutoHDR.exe.zip](https://github.com/Codectory/AutoHDR/files/7697661/AutoHDR.exe.zip)
[UserSettings.zip](https://github.com/Codectory/AutoHDR/files/7697662/UserSettings.zip)

Can also confirm that it crashes whenever I'm switching monitor, which has been discussed in another issue.

**Comment by GODzillaGSPB** [comment]
Can confirm, it does this when switching monitors. I'm currently playing RDR2 on my TV for better HDR and more immersion and use Auto HDR to switch on HDR. When I exit the game, AutoHDR switches off HDR as it should. And then I switch back to my pc monitor....and AutoHDR crashes.

Which is funny because I would've closed AutoHDR anyway. So...a feature maybe, can it read my mind? :D

**Comment by Codectory** [comment]
Fixed in 1.7.17

**Comment by RaasclartNinja** [comment]
This is still happening for me on 1.7.17.

Waking my computer from sleep causes the application to crash.

**Comment by RaasclartNinja** [comment]
Sure, log is attached. The computer was woken from sleep at 16:57
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7713396/AutoHDR.log)
.

**Comment by Codectory** [comment]
Please test again with 1.7.19

**Comment by RaasclartNinja** [comment]
Still crashing.
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7719728/AutoHDR.log)

**Comment by Codectory** [comment]
Does it work afte restart?

**Comment by Codectory** [comment]
Please try this one
[Release_AutoHDR_1.7.20_x64.zip](https://github.com/Codectory/AutoHDR/files/7719816/Release_AutoHDR_1.7.20_x64.zip)
[Release_AutoHDR_1.7.20_x86.zip](https://github.com/Codectory/AutoHDR/files/7719817/Release_AutoHDR_1.7.20_x86.zip)

**Comment by RaasclartNinja** [comment]
If I restart or start my computer from cold. The application is open in Task Manager but there is no tray icon, yet when I open a game it toggles HDR on and the tray icon then appears. 

I then closed the game, HDR stayed enabled the AutoHDR crashed. 

Reopened AutoHDR, opened the game again and HDR mode didn't get enabled and AutoHDR crashed again.

I've then reopened AutoHDR and it's working as intended. Getting some really inconsistent behaviour with this latest version.

[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7719830/AutoHDR.log)

**Comment by RaasclartNinja** [comment]
I have just done another sleep/wake test and AutoHDR has remained open without crashing.

**Comment by Codectory** [comment]
with 1.7.20?

**Comment by RaasclartNinja** [comment]
Will try that now.

**Comment by Codectory** [comment]
![image](https://user-images.githubusercontent.com/61698721/146198951-d7236445-05cb-4c79-a610-44c6da33d873.png)

**Comment by RaasclartNinja** [comment]
Ah, didn't see that message. Will test and report back.

**Comment by RaasclartNinja** [comment]
This is an example of the "restart/cold start" scenario: 
![image](https://user-images.githubusercontent.com/49550861/146199525-1c8a5540-e7a5-48ab-9a74-c938a843f4ca.png)

Application is open but no tray icon, attached the log for this point.
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7719915/AutoHDR.log)

It seems to take about 3 minutes to initialize. Here's the log after the tray icon has appeared.
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7719925/AutoHDR.log)

Not a big deal that there is a delay but just worth mentioning.

Now after it's initialized and I open up a game, it toggled HDR on, but when closing the game the application crashed leaving HDR enabled. Log attached after the crash.
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7719941/AutoHDR.log)

**Comment by Codectory** [comment]
Did you closed AutoHDR between these to entries?
2021.12.15 13:55:56:6573967 Info: Settings loaded
2021.12.15 13:55:56:6573967 Info: Initializing...

**Comment by Codectory** [comment]
Please try this one and send me the logs;
[Release_AutoHDR_1.7.21_x64.zip](https://github.com/Codectory/AutoHDR/files/7720036/Release_AutoHDR_1.7.21_x64.zip)
[Release_AutoHDR_1.7.21_x86.zip](https://github.com/Codectory/AutoHDR/files/7720037/Release_AutoHDR_1.7.21_x86.zip)

**Comment by RaasclartNinja** [comment]
> Did you closed AutoHDR between these to entries? 2021.12.15 13:55:56:6573967 Info: Settings loaded 2021.12.15 13:55:56:6573967 Info: Initializing...

No, I did not touch AutoHDR. I left it sitting open until it fully intialized.

> Please try this one and send me the logs; [Release_AutoHDR_1.7.21_x64.zip]

Will try this now.

**Comment by RaasclartNinja** [comment]
Here is the log after a "restart/cold boot". Seems to be loading up quickly now, although there is an error in the log.
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7720225/AutoHDR.log)

HDR was left enabled by mistake, opening a game caused AutoHDR to crash.
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7720236/AutoHDR.log)

**Comment by RaasclartNinja** [comment]
Tested again with HDR off this time. Fresh restart and again it's taking a few minutes for the tray icon to appear
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7720257/AutoHDR.log)

Tray icon is now loaded here
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7720265/AutoHDR.log)

Opening a game and it switched to HDR, closing the game disabled HDR and the application did not crash. So it's working as expected.

**Comment by Codectory** [comment]
Once again please:
[Release_AutoHDR_1.7.22_x64.zip](https://github.com/Codectory/AutoHDR/files/7720385/Release_AutoHDR_1.7.22_x64.zip)
[Release_AutoHDR_1.7.22_x86.zip](https://github.com/Codectory/AutoHDR/files/7720386/Release_AutoHDR_1.7.22_x86.zip)

**Comment by RaasclartNinja** [comment]
Seemed to load up instantly after a restart but when launching a game it crashed and didn't enable HDR.
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7720432/AutoHDR.log)

I reopened AutoHDR, loaded a game and again HDR wasn't enabled and the application crashed.
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7720443/AutoHDR.log)

**Comment by Codectory** [comment]
Do you use audio actions? I removed them for now, because they are a little bit buggy.  
So the steps were:
1. Start AutoHDR
2. Sleep
3. Resume
4. Reopen AutoHDR
5. Launch game directly
6. AutoHDR crashed


Is that correct?

**Comment by RaasclartNinja** [comment]
Nope, no audio actions. At this point i'm doing the following actions, I haven't tested the Sleep/Wake function yet as I can't even get .22 to work without crashing when I load a game.

Steps are:

1. Restart computer
2. Login
3. Load game
4. AutoHDR crashes and HDR is not enabled

If I test the Sleep/Wake function, the application is not crashing on .22 at present. But the app doesn't actually work (crashes when opening a game and no HDR enabled etc.)
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7720598/AutoHDR.log)

**Comment by Codectory** [comment]
Alright, so the crash is not related to sleep mode. Please send me you UserSettings.json

**Comment by RaasclartNinja** [comment]
Sure, sleep mode doesn't seem to be triggering a crash anymore. But the application seems to crash when opening a game, sometimes HDR get's enabled before the crash, sometimes it doesn't enable HDR before crashing.
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7720635/AutoHDR.log)

[UserSettings.txt](https://github.com/Codectory/AutoHDR/files/7720638/UserSettings.txt)

Had to renamed it to .txt to upload here.

**Comment by Codectory** [comment]
Can you test other games?

**Comment by RaasclartNinja** [comment]
Okay, even stranger. Other games seem to work as expected...
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7720707/AutoHDR.log)

I tried launching Halo Wars 2 after Halo Infinite and it crashed without enabling HDR. Weird as the application used to work fine with Halo Wars 2 before .22

**Comment by Codectory** [comment]
So just to make it clear. AutoHDR crashes, not Halo Wars 2 right?

**Comment by RaasclartNinja** [comment]
Yes, AutoHDR is crashing. Halo Wars 2 doesn't crash.
